# Site settings
title: "James Wynn Sr TW / BA"
description: "Resume for a Sr Technical Writer and Business Analyst."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "James Gaston Wynn"
resume_title:                   "Sr. Technical Writer and Business Analyst"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "wynn.james@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "512-698-9178"
# resume_contact_address:         "Austin, TX"

resume_header_contact_info:     "512-698-9178 â€¢ wynn.james@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I have over 20 years of experience as a documentation and process specialist, creating user manuals, knowledgebase guides, administrator guides, API references, online help, and animated online demos, and business analysis to develop use cases, UML/BPM workflow diagrams, and requirements documentation.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
resume_github_url:            "https://hedcannon.github.io/"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
# resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/james-wynn-a24b352/"
# resume_instagram_url:         "insert your Instagram URL here"
#  resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
